version: '3.8'

services:
  # LocalAI service
  localai:
    image: localai/localai:latest-aio-cpu
    container_name: localai-server
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    networks:
      - doc-insight-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main application service
  app:
    build: .
    container_name: document-insight-app
    ports:
      - "8000:8000"  # FastAPI
      - "7860:7860"  # Gradio
    environment:
      - DEEPSEEK_API_KEY=localai
      - DEEPSEEK_API_URL=http://localai:8080/v1/chat/completions
      - CACHE_TYPE=${CACHE_TYPE:-file}
      - ENABLE_PERFORMANCE_MONITORING=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./test_docs:/app/test_docs
      - ./logs:/app/logs
    depends_on:
      - localai
    networks:
      - doc-insight-network
    restart: unless-stopped
    command: ["/app/run_services.sh"]

networks:
  doc-insight-network:
    driver: bridge
    name: doc-insight-net

volumes:
  uploads:
  cache:
  models: